[package]
name = "uasm"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
clap = "2.5.2"
serde = "0.7.10"
serde_macros = "0.7.10"
serde_json = "0.7.1"
itertools = "0.4.16"
regex = "0.1.71"
